import {ALL} from './core.js';
export const seconds=ms=>`${(ms/1000).toFixed(1)} s`;
export function challengeViews(state,button,heading,table) {
 const best=state.challenge.best[table];
 return {
 choose(){const active=state.round&&state.round.phase!=='results';return `<section class="settings challenge-settings">${button('← Home','home','text-button')}${button('Personal bests','bests','text-button')}${heading('TIME CHALLENGE','One table. Twelve facts.','A shuffled round, with time to think. No time limit.')}<p>Answer time excludes the countdown and feedback. Each wrong answer adds <strong>5 seconds</strong>; you have one retry per fact.</p><div class="table-picker" role="group" aria-label="Challenge table">${ALL.map(t=>button(`<span>${t}</span><small>times table</small>`,`challenge-table:${t}`,`table-option${t===table?' selected':''}`,`aria-label="${t} times table" aria-pressed="${t===table}"`)).join('')}</div>${button('View full table','reference','secondary reference-open')}<p class="challenge-best">${best?`Personal best: <strong>${seconds(best.adjustedMs)}</strong> adjusted · ${best.score}/12 first try · ${best.errors} errors · ${best.day}`:'No personal best for this table yet.'}</p><p class="small muted">${table===state.guided.tables.at(-1)?'10 of 12 first-try answers also count toward your guided streak.':'This table grows mastery without changing your guided streak.'} Pausing, leaving the app or reloading means the round cannot set a personal best, but you can still finish and learn.</p>${active?`<p>Finish your paused ${state.round.mode==='challenge'?'challenge':'practice'} first. Only one round is active at a time.</p>${button(state.round.mode==='challenge'?'Resume challenge':'Resume practice','start','primary large')}`:button('Start challenge','challenge-start','primary large')}</section>`;},
 countdown(){return `<section class="challenge-countdown">${button('← Pause','home','text-button')}${heading('TIME CHALLENGE',`${state.round.table} times table`)}<p>Get ready. The clock starts with your first question.</p><p id="countdown" role="status" aria-label="Starting in 3 seconds">3</p><p class="small muted">No time limit. Take it one fact at a time.</p></section>`;},
 results(){const r=state.challenge.results.find(x=>x.id===state.round.id),pb=state.challenge.best[r.table];return `<section class="results challenge-results">${heading('TWELVE FACTS. ONE STEP FORWARD.','Challenge complete.',`${r.table} times table`)}<dl class="time-breakdown"><div><dt>Answer time</dt><dd>${seconds(r.elapsedMs)}</dd></div><div><dt>Penalties · ${r.errors} wrong ${r.errors===1?'answer':'answers'}</dt><dd>+ ${seconds(r.penaltyMs)}</dd></div><div class="adjusted-total"><dt>Adjusted time</dt><dd>${seconds(r.adjustedMs)}</dd></div></dl><p id="score"><strong>${r.score} / 12</strong> correct on your first try (${Math.round(r.score/12*100)}%)</p><p class="${r.newBest?'celebration':'small muted'}">${r.newBest?'A new personal best.':!r.recordEligible?'Interrupted round · not eligible for a personal best.':'Round saved. Keep practising at your own pace.'}</p>${pb?`<p>Table ${r.table} personal best: <strong>${seconds(pb.adjustedMs)}</strong> · ${pb.score}/12 · ${pb.errors} errors · ${pb.day}</p>`:''}<p>${r.added?`A new chapter: the ${r.added} times table is ready!`:r.guidedEligible?`${r.qualified?'A qualifying round.':'Keep practising. The guided streak starts fresh.'} ${state.guided.streak} / 3 toward the next table.`:'Your fact mastery grew. Guided progress is unchanged.'}</p><div class="actions">${button('Another challenge','challenge','primary')}${button('Personal bests','bests')}${button('Home','home')}${button('Progress','progress')}</div></section>`;}
 };
}
export function challengeHistory(state) {
 return `<section class="challenge-history"><h2>Time challenges</h2><h3>Personal bests</h3><ul class="history-list">${Object.values(state.challenge.best).map(r=>`<li>Table ${r.table} · <strong>${seconds(r.adjustedMs)}</strong> adjusted · ${r.score}/12 · ${r.errors} errors<time>${r.day}</time></li>`).join('')||'<li>No personal bests yet.</li>'}</ul><h3>Recent challenges</h3><ol class="history-list">${state.challenge.results.slice(-10).reverse().map(r=>`<li>Table ${r.table} · ${seconds(r.adjustedMs)} adjusted · ${r.score}/12 · ${r.errors} errors${r.recordEligible?'':' · Interrupted'}<time>${r.day}</time></li>`).join('')||'<li>No challenges completed yet.</li>'}</ol></section>`;
}
